[stack]
id = "heroku-18"
build-image = "heroku/heroku:18-cnb-build"
run-image = "heroku/heroku:18-cnb"

[lifecycle]
version = "0.9.3"

[[buildpacks]]
  id = "jkutner/minecraft"
  uri = "docker://jkutner/minecraft:latest"

[[order]]
  [[order.group]]
    id = "jkutner/minecraft"
